### ISSUE TITLE
rake aborted: ArgumentError: wrong number of arguments (given 2, expected 0)

### ISSUE THREAD

**Issue by palladius** [evan/echoe#23]
using echoe v4.6.6 to build my old gem: palladius/ric

 ```
bundle exec rake release --trace


** Execute pkg/ric-0.12.5.gem
cd pkg/ric-0.12.5
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 0)
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/echoe-4.6.6/lib/echoe/rubygems.rb:10:in `validate'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/package.rb:301:in `build'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/package.rb:134:in `build'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/package_task.rb:118:in `block (3 levels) in define'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:111:in `when_writing'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/package_task.rb:117:in `block (2 levels) in define'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:35:in `chdir'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/package_task.rb:116:in `block in define'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
/home/riccardo/git/ric/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<top (required)>'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/home/riccardo/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/riccardo/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => release => package => gem => pkg/ric-0.12.5.gem
```

code available in https://github.com/palladius/ric/

**Comment by palladius** [comment]
Adding env versions if needed

```$ rublurb 
== Ruby stuff ==
+ Versions:
+ Ruby   version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
+ Gem    version: 3.1.4
+ Bundle version: Bundler version 2.1.4
+ Rails  version: Rails 6.1.1
+ Facter version: 4.0.46
+ IRB    version: irb 1.2.7 (2020-09-19)
+ rbenv  version: rbenv 1.1.1-39-g59785f6
2.7.2 (set by /home/riccardo/.rbenv/version)

+ Paths:
+ Ruby   path: /home/riccardo/.rbenv/shims/ruby
+ Gem    path: /home/riccardo/.rbenv/shims/gem
+ Bundle path: /home/riccardo/.rbenv/shims/bundle
+ Rails  path: /home/riccardo/.rbenv/shims/rails
+ facter path: /home/riccardo/.rbenv/shims/facter
+ IRB    path: /home/riccardo/.rbenv/shims/irb
+ RbEnv  path: /home/riccardo/.rbenv/bin/rbenv
+ rvm    path: -

== Additional Linux/Darwin blurb ==
+ OS version:   Linux aspirina 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
+ Ubuntu stuff: No LSB modules are available.
  -Distributor ID:      Ubuntu
  -Description: Ubuntu 20.04.3 LTS
  -Release:     20.04
  -Codename:    focal
+ Debian stuff: bullseye/sid
+ RbEnv Ruby version:     2.7.2 (set by /home/riccardo/.rbenv/version)
+ Darwin Brew ruby stuff: /home/riccardo/git/sakura/bin/rublurb: line 31: brew: command not found
```
